# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BAC Calculator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BAC Calculator

# Add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'

# Add the pods for any other Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Firebase/Database'
pod 'FirebaseUI'
pod 'FirebaseUI/Auth'
pod 'GoogleSignIn'
end
